### ISSUE TITLE
Organization feature request

### ISSUE THREAD

**Issue by thantoldo** [helpyio/helpy#11]
Hi Scott!
Great work there :)

Is it possible to add the concept of 'organization' to the project? 
For example, the project will support multiple organizations where each organization has its own users, admins, posts, topics, users, forums, etc. It is like adding a new level of abstraction to the whole project.

This can be done right now by installing multiple versions of the app (setting up multiple databases accordingly) which is not practical at all. Is there any other 'easier' way to do it?

I think it would be a great feature.

Regards,

Thanos

**Comment by scott** [comment]
Hi Thanos,

Thanks for the idea!  If I understand you correctly, you are suggesting a "multi tenant" architecture, where multiple groups could share the same Helpy instance, in isolation?  (this could make server admin among other things quite a bit simpler for larger organizations)  Am I on the right path?

Unfortunately, I do not have an easier way to do it right now, and it seems like this would be a significant undertaking to add into the system.  That being said, it certainly seems useful for some I can add it to the backlog and maybe someone will consider working on it :)

Scott

Scott

**Comment by thantoldo** [comment]
Yes Scott, you are right, I'm suggesting a multi tenant architecture.

Maybe adding an organization model, an organization table field at the other models and altering all models a bit so they become organization aware, I think would be sufficient without altering anything else. Just basic functionality to start with. I could work sometime on this, unfortunately I can't consider when right now.

Regards,

Thanos

**Comment by scott** [comment]
Okay, a few other things to consider for a true multi-tenant version:

- Helpy would need a more robust user authorization capability- to silo agents into their own organization
- Interface/Workflow for adding new orgs/admins.  Also the concept of a "super admin"
- Major questions around i18n and settings per org

Thoughts?

Another possibility is creating a "product" tier of abstraction, that would allow for an independent set of forums and knowledge base for a a set of different products (rather than orgs).  Think of Apple.com support and how they have this for iMac and iPhone products, for example.

**Comment by thantoldo** [comment]
Well, the sky is the limit.

Depends on how you want to go on with helpy.
Start with basic functionality, like the super admin and organizations. i18n can be placed down the roadmap, not right from the beginning.

In the meanwhile, people's feedback could lead to one way or another. "Productizing" could be considered afterwards.

Just my 2c

Regards,

Thanos
