### ISSUE TITLE
Hardcoded User id=2 in view

### ISSUE THREAD

**Issue by alanq** [helpyio/helpy#1134]
In `app/views/admin/topics/_hidden_notes.html.erb` there is a hardcoded User id in line 4:

`		<%= avatar_image(User.find(2), size=40) %>
`

I had deleted the user with id 2 so kept getting errors on `Admin::TopicsController#update_topic`, which renders this partial.

Is this an oversight? I manually overrode another user id as a hack.

Thanks

**Comment by scott** [comment]
The system user (id 2... also sometimes labeled as HelpyBot) is used for notifications that cannot be attributed to a specific user, and if you remove it you'll run into many problems.

This code you mentioned is not hardcoded because it is possible to change the users name from "System" to something else.  In our cloud version we user "Helpy Bot" for example.
