### ISSUE TITLE
Feedback When Posting Response or Internal Note to Ticket

### ISSUE THREAD

**Issue by BenHagan** [helpyio/helpy#117]
Hello, first off, this looks like a really cool project, and I hope it does well.

I got an instance up, and while posting some test responses/internal notes I noticed that when I hit the submit button, there's no indication that my response was successfully posted.  This led me to click the submit button once more, and again no response.  I refreshed the page, and now see my response actually posted twice.  

So the functionality is working, in my opinion there just needs to be an indication to the user that the operation was successful.  Might also be good to remove the response text from the text field after successful posting.

**Comment by BenHagan** [comment]
Strangely enough it works fine on the version I deployed to Heroku, just not on DO.  Strange...

**Comment by scott** [comment]
Hey Ben!

Yeah this is because there is no SMTP server configured when you first install, which results in an exception (we're not using any kind of backend queue for sending email, yet at least.)  I am getting ready to launch a new release that changes the behavior so that it "just works" when you first install.  Glad you like Helpy.
