### ISSUE TITLE
Cloudinary storage alternative?

### ISSUE THREAD

**Issue by arrowcircle** [helpyio/helpy#129]
Hi!
Thank You for the great project!
Is there are any alternatives to cloudinary? Many people use S3 as well as static file storages.

**Comment by scott** [comment]
Currently the only option is cloudinary, but there have been many requests for an S3 option.  It is currently pretty low on the roadmap, but if someone submits a PR or builds an add-on that would help get it done quicker.  The challenge is that I think it would introduce a new dependency on imagemagick?

**Comment by arrowcircle** [comment]
Imagemagick will be required if processing is needed (resize, optimisation).
For server infrastructure is not a problem, it installs with simple apt-get or yum.

Main concern here is to separate cloudinary logic with carrierwave. It looks like carrierwave supports cloudinary. If we move all processing to carrierwave and add storage configuration to storage, we will loose cloudinary requirement.

@scott What do You think?

**Comment by arrowcircle** [comment]
Also, its possible to easily move support of custom storage to s3 only, and for local storage use https://github.com/minio/minio project

**Comment by Rynaro** [comment]
I have my own version of Helpy, running inside the company that I works.
I've made several changes inside Helpy to accept local storage file managing, and the only problem I faced, is the conflict with Cloudinary vendor Javascripts, conflicting with remotipart features.
I needed fully remove the Cloudinary, to my changes works as well.
PS: I remove Cloudinary feature because my company has a own file storage server. 
But, I don't see problem to make a config to "switch" features "Cloudinary <-> Other service"

**Comment by scott** [comment]
@Rynaro it would be awesome if you could package your work up as a PR with a config switch, and make it s3 compatible.

**Comment by arrowcircle** [comment]
@Rynaro Any updates?

**Comment by Rynaro** [comment]
@arrowcircle , I'm sorry about the lacks of updates. I'm very busy in these days.
Now, I adjusted my time, and I will maintain you updated of my work about this issue.
Again, I'm so sorry.
---
@scott , is interesting to Helpy has this feature to switch the file storage server?

**Comment by scott** [comment]
Just to close this out, Helpy 1.x now includes Carrierwave as the default.
