### ISSUE TITLE
Extract Widget into an Extension?

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#158]
I have been thinking that the javascript widget really should be provided as an optional extension, curious what others think of this idea.  My reasoning is that it is not functionality everyone may want to use, and furthermore I envision a future where you may be able to select between multiple widgets- simple KB oriented ones vs. full fledged chat oriented.

**Comment by jprberlin** [comment]
I think this is a good point. In an university project my class developed something similar using a Polymer Component. We also supported OAUTH2 there, so the widget can run in the scope of the authorized user. But this requires using polymer, so this is not a good solution i would recommend to use "in the wild" yet. Just mentioned it because it could be a long term vision.
But adaptability and extensibility for widget would be great.
