### ISSUE TITLE
Seeds required before expluatation Helpy

### ISSUE THREAD

**Issue by Nondv** [helpyio/helpy#180]
Hello there!
Sorry for my english. I hope you will understand.

[This](https://github.com/helpyio/helpy/blob/master/app/controllers/admin/topics_controller.rb#L81) smells bad and causes troubles.

Steps:

1) We installed Helpy but **forgot about seeds**.
2) We created test forum.
3) Then we had some troubles (internal server error) that were solved by rake db:seed.
4) Now we can't create ticket via `/admin/topics#new-discussion`, cuz of troubles with ids.

I believe that there're other similar errors.

**Comment by Rynaro** [comment]
Seeds provides a initial database configuration, if you don't run seeds first time, the database is incomplete in some features.
The `Forum.find(1) `, is a internal state of private messages. But, Helpy is your friend, you can make your own configurations inside the seeds to make your Helpy instance working with your needs.
I think maintain Forum id 1 as a private state is a best practice, because the Helpy code knows the id 1 is a private state, changing the Forum id state results in code review and refactoring to make Helpy works well.
