### ISSUE TITLE
Move bulk operations to background worker

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#222]
Currently if you select a bunch of messages and perform a bulk action, it is really slow.  This should be offloaded to a worker.

**Comment by scott** [comment]
Hi @shaktik1989 I didn't have time to write up any additional requirements of the API work yet, but you can take a look at this issue instead.  If you look in https://github.com/helpyio/helpy/blob/master/app/controllers/admin/topics_controller.rb

There are actions for changing assignee, privacy, status, etc.  This provides the ability to update the status of one (or a group of) discussions.  They all accept an array of params and iterate through topics one by one.  This can get quite slow for bulk operations- when an action is taken on many topics at once.  It would be great to offload this to a worker.  It also mean the JS should still update the UI independent of the model data having actually changed since they will now be decoupled.

**Comment by olliebennett** [comment]
Would it be more appropriate to improve the performance of the queries involved instead? Seems that moving to a background worker is just working around the fact we're doing inefficient things, and also leads to potential discrepancies between front and back-end if the UI updates without confirmation that things have changed server-side (i.e. if the job fails).

To take your `admin/topics_controller.rb` example, there's some very low-hanging fruit. Below are some examples from the `assign_agent` method:

- Multiple `.find` queries instead of one bulk select
    ```ruby
    # before
    params[:topic_ids].each do |id|; @topic = Topic.where(id: id).first
    # after
    Topic.where(id: params[:topic_ids]).each do |topic|
    # note: this no longer crashes if an invalid topic ID is provided, which may or may not be desired.
    ```

- We're running `User.find(params[:assigned_user_id])` inside a loop but it's not changing (so we should calculate it before the loop).

- If `unless params[:assigned_user_id].blank?` is true, we probably don't need to bother looping through anything?

- `@topic.assign` is re-calculating the message (for i18n) again re-calculating `User.find(assigned_to).name` each time; we could potentially optimise this as an `update_all` (or other bulk create / update logic) if we were clever about it, or at least avoid instantiating the `@topic` objects. That may be going further than necessary though.

- Should we use `@count` instead of `params[:topic_ids].count > 1` or is that deliberate? If deliberate, we could check `Topic.where(id: params[:topic_ids])` against `params[:topic_ids].length` instead?

- `@count = @count + 1` => `@count += 1`

- Also it seems there are a few unnecessary instance variables (`@minutes` is only ever 0).

If @shaktik1989 is happy to attempt the above instead of moving to background job, I'm keen to offer any more suggestions / review PRs. Likewise I could tackle this if nobody else is up for it, before we dive into a more complex solution than may be needed.

**Comment by scott** [comment]
I agree I think there are some opportunities there for refactoring and making it more performant but I suspect it will still be slow enough to warrant delaying it when there are a large number of messages being acted on all at once.  This is because some/all of the actions do add a new `Post` to each`Topic` so you could in theory have 20+ insert statements.

However you gave me another idea now that we have the concept of background workers in Helpy- that is many of the admin actions include one or more calls to Google Analytics, which could easily be done asynchronously and would probably yield a nice boost in performance.  It has been a while since I have looked at that code but I will make a note.

**Comment by scott** [comment]
#225

**Comment by scott** [comment]
Just tested this and moving just the GA call to a worker cut the action load time by about 50%.

**Comment by olliebennett** [comment]
Awesome! Nice job - because it's inside a loop it would also make sense to build the list of GA events and fire them all at once; not sure whether the logic we're using supports that though.

Do you want me to take a look at other performance improvements for this or @shaktik1989 are you keen? Either way - great progress if you've already shaved 50% off, so hopefully it's possible we can still avoid the background job for the whole loop.

**Comment by shaktik1989** [comment]
Thanks @olliebennett for your thoughts on this, I just got the time to read the whole conversation and I will definitely like to work on the points that you raise and surely appreciate your review feedbacks on the PRs.

**Comment by olliebennett** [comment]
Referencing Shakti's work on refactoring the `TopicsController` (bulk assign agent): #238
