### ISSUE TITLE
rake tasks failing

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#260]
`rake assets:precompile` gives `fatal: Not a git repository (or any of the parent directories): .git` error. I've tried every suggestions online but still could not fix it

even with `-v` it doesn't give me anything more.

**Comment by olliebennett** [comment]
Hey @hadifarnoud - it sounds like you've got a corrupted `.git` directory or something, rather than anything to do with the helpy code itself. Can I suggest you `git clone` helpy into a different directory (temporarily) and see if you can run the `rake` task there? I've check on `master` just now and it's working fine for me.
