### ISSUE TITLE
Add API endpoint to create a ticket with an email address

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#616]
The current endpoint expects a userID which means that you either have to look up the user or create them before creating a ticket.  This would bake that logic into one call, similar to the way the `email_processor` and `topics#create work.`

**Comment by spajus** [comment]
This would be very useful. Right now even looking up the user by email is cumbersome, since api only allows listing all users. And what if you have thousands?

**Comment by GPrimola** [comment]
Hi guys, I'm going to work on this issue, ok?

**Comment by GPrimola** [comment]
Hi @scott, as we already started a discussion about naming conventions for this endpoint at slack, I'm bringing this discussion here for documentation purposes.

Well, I asked you about any naming conventions, because as this issue is requiring a new endpoint we would come up with something like `post /api/v1/tickets/create_with_email.json` which I think is a little bit odd.
My suggestion would be to extend the already existing `post /api/v1/tickets.json`. We keep the `user_id` param for compatibility reasons, and add a new `user` parameter where can be passed an email.
A snippet of the `user` object json schema would be: 

```json
"user": {
  "type": "object",
  "properties": {
    "email": { "type": "string" },
    "name": { "type": "string" },
    "password": { "type": "string" }
  },
  "required": ["email"]
}
```

The only required property would be `email`, and the endpoint would deal with non-registered users properly.

I understand that this approach (of extend the already existent endpoint `post /api/v1/tickets.json`) would ad logic, and thus complexity, to an "atomic" action designed only for create tickets.
But due to the oddity of the naming, I think would be better to extend. As my view is very limited about this project, I'm bringing this discussion here.

What do you think of this?

**Comment by GPrimola** [comment]
As for the `password` attribute is another thing I would bring. I was reading the code of `email_processor` and I would do something like that: a generated password that expires. I think that's most appropriate for this case.

**Comment by scott** [comment]
I think this is a good approach as long as it does not break the expected current behavior of the endpoint.  People have built integrations based on the current implementation which requires a `user_id` param.  We could relax that to make it require either the userID or email address which would create a new user and use that instead.

**Comment by GPrimola** [comment]
That's exactly what I'm suggesting. I am aware about the existence of integrations and any changes in the interface would break any communication with the API.

But relaxing the user_id parameter would not make any difference to any existing integrations. :)

**Comment by scott** [comment]
#628
