### ISSUE TITLE
Creating a new ticket as an admin and leaving the email field blank, breaks the open tickets view

### ISSUE THREAD

**Issue by rschaerer** [helpyio/helpy#69]
Creating as an admin a new ticket on behalf of a customer via the admin interface (`/admin/tickets/new`) and leaving the `Email` field blanks breaks the view of "new tickets") (`/admin/tickets?locale=de&status=new`) because the database field `user_id` in the tables `topics` and `posts` is `NULL`.
# Proposed solutions to fix this
- make the email field mandatory
- assign a `no e-mail provided` user to tickets witout an e-mail entered

Peronally, I'd prefer the second option, because we have sometimes customers without an e-mail and just a phone numer. If this bug get's fixed by implementing the first suggestion, then we would have to enter ad dummy e-mail address by ourself to record such tickets. this would lead in missinformation about users, because every ticket would be assigned to the same dummy email address user.
# More context, if needed:
- When a non logged in user tries to post a new ticket on `/de/topics/new` without entering data in the email field, the form returns an error and everything works as expected.
- To fix tickets without an email entered on the database level I had to assign the entry in the `topics` table with an `user_id`other than NULL. After doing this, I could view the new tickets view again, but the post isn't viewable too when i try to click it. To fix this, I had to assign once more an `user_id` to the entry in the `posts` table of my PostgreSQL database.

**Comment by scott** [comment]
Thanks for this, we'll take a look at see what we can do to fix it :)

**Comment by olliebennett** [comment]
This is certainly an interesting problem.

I'd propose that a short-term fix (to avoid actual breakage of the system) would be to require the email input by the admin when creating the ticket.

As for the longer-term solution, I agree it'd be nice to avoid admins having to enter `dummy@example.com`.

My thought on some (non-ideal) options:

- One single "no-email" user. Not sufficient because - to use the example above - the user opening the ticket may have other data (such as a phone number) which would want to be tracked on a per-user basis and not on the single "no-email" user.

- One new "no-email" user automatically created per "email-less ticket". This would let us store the phone number etc. on a per-user basis. This would be a tricky one to implement, as `devise` requires the presence of `email` to allow for all the registration / validation / password reset / confirmation etc. that comes as standard. If we just generated something like `user-<random-numbers>@example.com`, that could work. It might get ugly as we'd have to think how to display these sorts of email, and/or at least indicate that they were "fake" somehow.

- Accepting a "User Remote ID" which would be the ID of the user in the external system. This would still leave the validation issue of blank emails though. Furthermore, in some cases the "remote ID' may be irrelevant or impossible to identify.

- We could have some kind of `User Profile` model for which an email can optionally be set; the UserProfile can then be "claimed" by a real user if/when they come to use the system themselves.

**Comment by rschaerer** [comment]
Thank you very much for the detailed analysis of this issue, @olliebennett. Your insight made me think about the challenge to implement this in a good way, without changing the fundamental user authentication model helpy uses right now.

Another (non-ideal but good to go) possibility I can think of is something similar like your second point **"One new "no-email" user automatically created per "email-less ticket"."**

We could add a `no-email` button next to the e-mail field (just in the admin view, for all user sumittet tickets email should stay mandatory, I think). If this button is clicked, the Email address field is filled with something like `NO-EMAIL-USER-#($ticketnumber)@($no-email-domain)`. For example `NO-EMAIL-USER-#51@ourdomain.org`, where `no-email-domain` can be set up in the user config file.

This way, replies to tickets of such an user still can be entered into helpy, and maybe an agents misses the fact, that this user can't be contacted this way. However we can track such agent errors by getting the email to a defined domain. Maybe this implemention is just one step away from disabling the radio button `post_kind_reply` in the form `Reply to this Topic:` and therefore, make just notes to this ticket possible?

The positive side of this implementation is, that it might be quite easy to roll out and other contact information can be added to these unique users.

In the end, my technical understanding is not good enough to appropriate evaluate the required code changes.

**Comment by scott** [comment]
@rschaerer @olliebennett I just merged some changes that put a "band aid" on this, by preventing form submission if the fields are empty.  This is a nice UX effect, but does not solve the underlying problem or the use case outlined above.  The good thing is the UI won't need to be reloaded if you fail to complete the form, the bad thing is if a user does not have an email, the problem still exists.

**Comment by rschaerer** [comment]
I think this shouldn't be considered a bug anymore (since 17 Mar) but the title of the discussion should be changed as well! I'd like to close this issue and reopen another one, assigned to the "philosophical" discussion. But maybe we just forget about all this, until it comes up with an actual user case and just close this issue an d do nothing more about it?

What to do now?
