### ISSUE TITLE
Docker install question

### ISSUE THREAD

**Issue by SeaDude** [helpyio/helpy#713]
What is meant by step 2. of the installation?:
_**Edit files for your configuration Edit docker/.env file and enter the necessary information and passwords. Edit docker/Caddyfile if you wish to include your website's URL and enable SSL.**_

- Where is this docker/.env file? 
- What do the necesary "information" and "passwords" refer to? 
- Where is this docker/Caddyfile?

I'm just getting started with Docker so excuse me if i'm not versed. I'd be happy to update your install instructions to be more verbose if you give the info. 

Thanks!

**Comment by lidimayra** [comment]
There's actually a _docker_ directory 🙂

> Where is this docker/.env file?

It refers to [this file](https://github.com/helpyio/helpy/blob/master/docker/.env.sample). Since this is just a sample, you must copy it and name it _.env_

> What do the necesary "information" and "passwords" refer to?

Your Postgres username and password. You must inform it in [#L2](https://github.com/helpyio/helpy/blob/master/docker/.env.sample#L2) and [#L3](https://github.com/helpyio/helpy/blob/master/docker/.env.sample#L3) in order to connect to your database.

> Where is this docker/Caddyfile?

In [here](https://github.com/helpyio/helpy/blob/master/docker/Caddyfile).
