### ISSUE TITLE
Clientside validations not working for groups new/edit forms

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#824]
In `Admin::GroupsController` the `new` and `edit` views instead of preventing submission, it is silently failing by displaying the index.

**Comment by titchimoto** [comment]
Hi @scott 

Just used the test app and I see what you mean about it just failing silent and just re-directing to the index with no warnings. Would love and to work on this and submit a PR for it, if you're accepting submissions?

**Comment by scott** [comment]
Hey @titchimoto that would be great!

**Comment by titchimoto** [comment]
Hey @scott - So I got everything up and running locally, and the same(ish) issue was occurring. Although, it only seemed to be doing it on the `new` view rather than the `edit` view as you mentioned.

Now, I'm not very familiar with the `ActsAsTaggableOn` so, I'm not sure if I'm just missing something super obvious with it, but I just refactored the controller check a little to prevent it sneaking through. Am I right in saying there's no specific model for the admin/groups but it simply gets added on with `ActsAsTaggableOn` ?

Alas, I have it working locally here, any attempt to submit the form without the required 'name' field will cause an error & use the validation `can't be blank` like all the other inputs. If that is not left blank, the form processes as expected, and the new group appears.

I'll submit the PR now, let me know if there's anything really obvious I'm missing! Cheers, Rich.
